version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: ev-battery-postgres
    environment:
      POSTGRES_DB: battery_health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=timescaledb

volumes:
  postgres_data: