version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg14
    container_name: ev-battery-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-battery_health}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "127.0.0.1:5432:5432"  # Bind only to localhost for security
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=timescaledb
    restart: unless-stopped

volumes:
  postgres_data: